[package]
name = "rust-discord-record"
version = "0.1.0"
authors = ["Frank <frank_spitulski@yahoo.com>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-trait = "0.1"
audiopus = "0.2"
byteorder = "1"
chrono = "0.4"
circular-queue = "0.2"
lockfree = "0.5"
ogg = "0.9"
ogg-opus = "0.1"
rand = "0.8"
songbird = "0.3"

[dependencies.serenity]
version = "0.11"
features = ["cache", "http", "client", "framework", "standard_framework", "voice", "rustls_backend"]

[dependencies.tokio]
version = "1"
features = ["macros", "rt-multi-thread", "time"]
