[package]
name = "rust-discord-record"
version = "0.1.0"
authors = ["Frank <frank_spitulski@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
rodio = "0.13"
songbird = "0.1"
circular-queue = "0.2"
hound = "3.4"
cpal = "0.13"

[dependencies.serenity]
version = "0.10"
features = ["cache", "http", "client", "framework", "standard_framework", "voice", "rustls_backend"]

[dependencies.tokio]
version = "1.0"
features = ["macros", "rt-multi-thread", "time"]