[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=skylake"]
[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=skylake"]
[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-cpu=skylake"]
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=skylake"]
[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=native"]
